defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local


obs_width: 64
obs_height: 64
max_step: 1000

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
save_video: true
save_train_video: true
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 1024

explorer:
  _target_: models.Explorer
  obs_channel: ??? # to be specified later
  action_dim: ??? # to be specified later
  lr: ${lr}
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  nb_ld_mlp: 5
  state_dim: 512
  hidden_dim: 2048
  ld_hidden_dim: 2048
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  nstep: ${nstep}
  discount: ${discount}

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm